2018-05-21 12:14:20.207 ERROR test 
2018-05-21 12:15:35.059 ERROR test 
2018-05-21 12:16:01.558 ERROR selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Error: selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
    at PythonShell.parseError (/Users/ahmedhatem/Desktop/SPES-PE/App/node_modules/python-shell/index.js:184:17)
    at terminateIfNeeded (/Users/ahmedhatem/Desktop/SPES-PE/App/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/Users/ahmedhatem/Desktop/SPES-PE/App/node_modules/python-shell/index.js:89:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    ----- Python Traceback -----
    File "scripts/script.py", line 18, in <module>
      driver = webdriver.Chrome('C:/Users/kimoa/OneDrive/Desktop/final/SPES-PE/App/scripts/chromedriver.exe')
    File "/Library/Python/2.7/site-packages/selenium-3.12.0-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
      self.service.start()
    File "/Library/Python/2.7/site-packages/selenium-3.12.0-py2.7.egg/selenium/webdriver/common/service.py", line 83, in start
      os.path.basename(self.path), self.start_error_message) 
2018-05-21 12:17:04.869 ERROR selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Error: selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
    at PythonShell.parseError (/Users/ahmedhatem/Desktop/SPES-PE/App/node_modules/python-shell/index.js:184:17)
    at terminateIfNeeded (/Users/ahmedhatem/Desktop/SPES-PE/App/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/Users/ahmedhatem/Desktop/SPES-PE/App/node_modules/python-shell/index.js:89:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
    ----- Python Traceback -----
    File "scripts/script.py", line 18, in <module>
      driver = webdriver.Chrome('C:/Users/kimoa/OneDrive/Desktop/final/SPES-PE/App/scripts/chromedriver.exe')
    File "/Library/Python/2.7/site-packages/selenium-3.12.0-py2.7.egg/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
      self.service.start()
    File "/Library/Python/2.7/site-packages/selenium-3.12.0-py2.7.egg/selenium/webdriver/common/service.py", line 83, in start
      os.path.basename(self.path), self.start_error_message) 
2018-05-21 12:17:32.984 ERROR Error: selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 
2018-05-21 12:17:48.372 ERROR Error: selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 
2018-05-21 12:18:07.594 ERROR Error: selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 
2018-05-21 12:18:27.437 ERROR Error: selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
 
